---
deployment:
  tasks:
    - export DEPLOYPATH=/home/bouncer/public_html/
    - /bin/cp -R index.html $DEPLOYPATH
    - /bin/cp -R demo $DEPLOYPATH
    - /bin/cp demo/.htaccess $DEPLOYPATH/demo/.htaccess
    - /bin/cp demo/admin/.htaccess $DEPLOYPATH/demo/admin/.htaccess
