---
deployment:
  tasks:
    - export DEPLOYPATH=/home/bouncer/public_html/
    - /bin/cp -R index.html $DEPLOYPATH
    - /bin/cp -R demosite $DEPLOYPATH
    - /bin/cp -R demoadmin $DEPLOYPATH
    - /bin/cp demosite/.htaccess $DEPLOYPATH/demosite/.htaccess
    - /bin/cp demoadmin/.htaccess $DEPLOYPATH/demoadmin/.htaccess
